# Generated by Django 5.1.6 on 2025-04-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='type_identification',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='user',
        ),
        migrations.DeleteModel(
            name='TypeIdentification',
        ),
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
    ]
