# Generated by Django 5.1.6 on 2025-04-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_area_created_at_area_updated_at_clause_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractclause',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='contractclause',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
